export const GameList = {
  // special
  f120162018: {
    en: "F1 2016-2018",
    cn: "F1 2016-2018",
    unit: "",
    type: "cmf1-16-18",
    digits: 2,
  },
  f120192020: {
    en: "F1 2019-2020",
    cn: "F1 2019-2020",
    unit: "",
    type: "cmf1-19-20",
    digits: 1,
  },
  f12021: {
    en: "F1 2021+",
    cn: "F1 2021+",
    unit: "",
    type: "cmf1-21",
    digits: 0,
  },
  // hfov
  richardburnsrally: {
    en: "Richard Burns Rally",
    cn: "理查德伯恩斯拉力赛RBR",
    unit: "rad",
    type: "hfov-rad",
    digits: 4, // 小数点后位数
  },
  projectcars12: {
    en: "Project Cars 1/2",
    cn: "赛车计划1/2",
    unit: "°",
    type: "hfov-deg",
    digits: 0,
  },
  ams2: {
    en: "Automobilista 2",
    cn: "AMS2",
    unit: "°",
    type: "hfov-deg",
    digits: 0,
  },
  eurotrucksim: {
    en: "Euro Truck Simulator",
    cn: "欧洲卡车模拟，美洲卡车模拟",
    unit: "°",
    type: "hfov-deg",
    digits: 0,
  },
  raceroom: {
    en: "RaceRoom Experience",
    cn: "RaceRoom",
    unit: "°",
    type: "hfov-deg",
    digits: 1,
  },
  iracing: {
    en: "iRacing",
    cn: "iRacing",
    unit: "°",
    type: "hfov-deg",
    digits: 0,
  },
  // vfov
  dirtrally12: {
    en: "Dirt Rally 1/2",
    cn: "尘埃拉力系列 Dirt Rally 1/2",
    unit: "°",
    type: "vfov-degx2",
    digits: 0,
  },
  gridautosport: {
    en: "GRID Autosport",
    cn: "GRID超级房车赛：赛车运动",
    unit: "°",
    type: "vfov-degx2",
    digits: 1,
  },
  acacc: {
    en: "Assettocorsa, Assetto Corsa Competizione",
    cn: "神力科莎AC，神力科莎竞技ACC",
    unit: "°",
    type: "vfov-deg",
    digits: 1,
  },
  isiengine: {
    en: "rFactor, Automobilista, Game Stock Car",
    cn: "rFactor, AMS, 等ISI引擎",
    unit: "°",
    type: "vfov-deg",
    digits: 0,
  },
  isiengine2: {
    en: "rFactor 2",
    cn: "rFactor 2",
    unit: "°",
    type: "vfov-deg",
    digits: 0,
  },
  eawrc: {
    en: "EA WRC",
    cn: "EA WRC",
    unit: "",
    type: "vfov-deg",
    digits: 0,
  },
  // special vfov
  gtr2: {
    en: "GTR 2",
    cn: "GTR 2",
    unit: "",
    type: "vfov-gtr2",
    digits: 1,
  },
  race07: {
    en: "Race 07",
    cn: "Race 07",
    unit: "",
    type: "vfov-race07",
    digits: 1,
  },
};
